### ISSUE TITLE
How do I convert SVG content to ImageSource?

### ISSUE THREAD

**Issue by meJevin** [ElinamLLC/SharpVectors#198]
Is there a way to convert SVG content to `ImageSource` using this library?

Context:
In my project I have a converter which converts one of my models to `ImageSource`. I have SVG content ready to go, but haven't found a way to convert that into an `ImageSource`.

I've tried the following:

```
var cnv = new ImageSvgConverter(new WpfDrawingSettings()
{
    IncludeRuntime = true,
    TextAsGeometry = true,
});

var result = cnv.Convert(tempSVGFilePath);
```

I'm saving SVG content to a temporary file and I'm trying to convert the local file to `ImageSource` via `ImageSvgConverter` . But I'm getting an empty exception when executing the last line of code. 

Stack trace of that exception is:
```
   at SharpVectors.Dom.Css.CssColor.ParseColor(String str)
   at SharpVectors.Dom.Css.CssColor..ctor(String str)
   at SharpVectors.Dom.Css.CssPrimitiveRgbValue.OnSetCssText(String cssText)
   at SharpVectors.Dom.Css.CssPrimitiveRgbValue..ctor(String cssText, Boolean readOnly)
   at SharpVectors.Dom.Css.CssPrimitiveValue.Create(Match match, Boolean readOnly)
   at SharpVectors.Dom.Css.CssValue.GetCssValue(String cssText, Boolean readOnly)
   at SharpVectors.Dom.Css.CssStyleDeclaration.GetPropertyCssValue(String propertyName)
   at SharpVectors.Dom.Css.CssStyleDeclaration.GetStylesForElement(CssCollectedStyleDeclaration csd, Int32 specificity)
   at SharpVectors.Dom.Css.CssXmlElement.GetComputedStyle(String pseudoElt)
   at SharpVectors.Dom.Svg.SvgStyleableElement.GetComputedStyle(String pseudoElt)
   at SharpVectors.Dom.Css.CssXmlElement.GetComputedCssValue(String propertyName, String pseudoElt)
   at SharpVectors.Renderers.Wpf.WpfRendering.SetClip(WpfDrawingContext context)
   at SharpVectors.Renderers.Wpf.WpfRendering.BeforeRender(WpfDrawingRenderer renderer)
   at SharpVectors.Renderers.Wpf.WpfSvgRendering.BeforeRender(WpfDrawingRenderer renderer)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.RenderElement(ISvgElement svgElement)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.Render(ISvgElement svgElement)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.Render(ISvgDocument docElement)
   at SharpVectors.Renderers.Wpf.WpfDrawingRenderer.Render(ISvgDocument node)
   at SharpVectors.Converters.ImageSvgConverter.ProcessFile(String fileName, String imageFileName)
   at SharpVectors.Converters.ImageSvgConverter.Convert(String svgFileName, String imageFileName)
   at SharpVectors.Converters.ImageSvgConverter.Convert(String svgFileName)
   at PVScan.Desktop.WPF.Converters.BarcodeImageConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture) in C:\Users\mejev\Desktop\Dev\Personal\PVScan\Source\Desktop\Windows\PVScan.Desktop.WPF\Converters\BarcodeImageConverter.cs:line 63
```

**Comment by meJevin** [comment]
SVG that I'm trying to load:

```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" version="1.2" baseProfile="tiny" shape-rendering="crispEdges" viewBox="0 0 600 600" viewport-fill="rgb(255,255,255)" viewport-fill-opacity="1" fill="rgb(0,0,0)" fill-opacity="1" style="background-color:rgba(1)">
  <rect x="90" y="90" width="20" height="140"/>
  <rect x="90" y="250" width="40" height="40"/>
  <rect x="90" y="330" width="20" height="20"/>
  <rect x="90" y="370" width="20" height="140"/>
  <rect x="110" y="90" width="120" height="20"/>
  <rect x="110" y="210" width="120" height="20"/>
  <rect x="110" y="370" width="120" height="20"/>
  <rect x="110" y="490" width="120" height="20"/>
  <rect x="130" y="130" width="60" height="60"/>
  <rect x="130" y="290" width="100" height="20"/>
  <rect x="130" y="330" width="20" height="20"/>
  <rect x="130" y="410" width="60" height="60"/>
  <rect x="150" y="250" width="20" height="20"/>
  <rect x="170" y="330" width="20" height="20"/>
  <rect x="190" y="270" width="20" height="60"/>
  <rect x="210" y="110" width="20" height="120"/>
  <rect x="210" y="250" width="40" height="20"/>
  <rect x="210" y="330" width="40" height="20"/>
  <rect x="210" y="390" width="20" height="120"/>
  <rect x="230" y="270" width="40" height="20"/>
  <rect x="230" y="310" width="20" height="40"/>
  <rect x="250" y="110" width="20" height="40"/>
  <rect x="250" y="170" width="20" height="80"/>
  <rect x="250" y="290" width="20" height="40"/>
  <rect x="250" y="350" width="20" height="40"/>
  <rect x="250" y="430" width="60" height="20"/>
  <rect x="250" y="470" width="40" height="40"/>
  <rect x="270" y="170" width="40" height="40"/>
  <rect x="270" y="310" width="40" height="20"/>
  <rect x="270" y="390" width="20" height="20"/>
  <rect x="270" y="450" width="20" height="60"/>
  <rect x="290" y="90" width="20" height="60"/>
  <rect x="290" y="210" width="20" height="20"/>
  <rect x="290" y="250" width="60" height="20"/>
  <rect x="290" y="290" width="20" height="40"/>
  <rect x="290" y="490" width="20" height="20"/>
  <rect x="310" y="130" width="20" height="20"/>
  <rect x="310" y="170" width="40" height="20"/>
  <rect x="310" y="270" width="20" height="40"/>
  <rect x="310" y="330" width="20" height="20"/>
  <rect x="310" y="370" width="40" height="20"/>
  <rect x="310" y="450" width="20" height="40"/>
  <rect x="330" y="90" width="20" height="40"/>
  <rect x="330" y="150" width="20" height="40"/>
  <rect x="330" y="210" width="20" height="20"/>
  <rect x="330" y="310" width="120" height="20"/>
  <rect x="330" y="410" width="60" height="20"/>
  <rect x="330" y="470" width="20" height="20"/>
  <rect x="350" y="270" width="20" height="20"/>
  <rect x="350" y="330" width="40" height="40"/>
  <rect x="350" y="430" width="60" height="40"/>
  <rect x="350" y="490" width="20" height="20"/>
  <rect x="370" y="90" width="20" height="140"/>
  <rect x="370" y="250" width="60" height="20"/>
  <rect x="370" y="290" width="20" height="180"/>
  <rect x="390" y="90" width="120" height="20"/>
  <rect x="390" y="210" width="120" height="20"/>
  <rect x="390" y="270" width="20" height="80"/>
  <rect x="390" y="470" width="20" height="40"/>
  <rect x="410" y="130" width="60" height="60"/>
  <rect x="410" y="290" width="40" height="40"/>
  <rect x="410" y="350" width="20" height="40"/>
  <rect x="430" y="330" width="20" height="40"/>
  <rect x="430" y="410" width="20" height="40"/>
  <rect x="430" y="470" width="20" height="40"/>
  <rect x="450" y="250" width="40" height="20"/>
  <rect x="450" y="290" width="20" height="20"/>
  <rect x="450" y="450" width="20" height="20"/>
  <rect x="450" y="490" width="40" height="20"/>
  <rect x="470" y="270" width="40" height="20"/>
  <rect x="470" y="310" width="20" height="100"/>
  <rect x="470" y="430" width="40" height="20"/>
  <rect x="490" y="110" width="20" height="120"/>
  <rect x="490" y="290" width="20" height="60"/>
  <rect x="490" y="410" width="20" height="60"/>
</svg>
```

**Comment by meJevin** [comment]
Ispecting https://github.com/ElinamLLC/SharpVectors/blob/96d009ce54a5057761ca36190d73478c97b66af4/Source/SharpVectorCss/Css/CssColor.cs#L395

**Comment by meJevin** [comment]
Yup, my SVG has `rgba(1)` for some reason....

**Comment by meJevin** [comment]
Fixed the issue on my end. But now I'm left with the following. Apparently this converter just saves an SVG as a PNG file... So I guess I'm using the wrong thing.

**Comment by paulushub** [comment]
> Yup, my SVG has `rgba(1)` for some reason....

`rgba` is supported but expects 4 parameters. I have not seen the single parameter example before, used [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value) for references.
But since this file opens in **Inkspace**, I will add the single value parameter support.

> Is there a way to convert SVG content to ImageSource using this library?

Try the following...
```cs
var cnv = new FileSvgConverter(new WpfDrawingSettings()
{
    IncludeRuntime = true,
    TextAsGeometry = true,
});

var result = new DrawingImage(cnv.Read(tempSVGFilePath));
```
There are also markup extensions... (see **\TutorialSamples\ConverterSamplesWpf** directory for more examples)
```xml
<Image Source="{Binding Converter={svgc:SvgImageConverter AppName=SvgImageBindingSample}, 
ConverterParameter=/Resources/Binding.svg, Mode=OneWay}" Width="24" Height="24"/>
```

**Comment by meJevin** [comment]
@paulushub I was actually about to make a pull request myself fixing that. Really love this library. Will gladly explore it more and help if I can 👍 

About your solution I will try it in the next couple of days. Thank you so much.

**Comment by meJevin** [comment]
You're also right, that `rgba(1)` is an incorrect format for `rgba`. I'm not sure why my svg even has it.. However, yes, this should not throw an Exception, it should just be skipped as css value with incorrect format.

**Comment by paulushub** [comment]
> I was actually about to make a pull request myself fixing that.

Sorry, I deprived you of that! PR are always welcomed, and there are lots of tasks and issues remaining!!!

**Comment by meJevin** [comment]
@paulushub, thank you so much! Your solution worked! We can close this one 👍
